FROM bitnami/spark:3.5.4

USER root

# 필수 패키지 설치
RUN install_packages \
    gcc \
    g++ \
    make \
    pkg-config \
    libfreetype6-dev \
    libpng-dev \
    libjpeg-dev \
    fontconfig \
    python3-dev \
    python3-pip \
    fonts-nanum

# 폰트 캐시 갱신
RUN fc-cache -fv

# Python 패키지 설치
RUN pip install --upgrade pip && \
    pip install --no-cache-dir \
    wordcloud \
    konlpy \
    matplotlib==3.8.3 \
    seaborn==0.13.2 \
    reportlab==4.1.0

USER 1001
