# 필수 기본 설정
jobmanager.rpc.address: jobmanager

# 메모리 명시
jobmanager.memory.process.size: 1024m
taskmanager.memory.process.size: 1024m

# 슬롯 수
taskmanager.numberOfTaskSlots: 2

# Prometheus 메트릭 수집
metrics.reporter.prom.class: org.apache.flink.metrics.prometheus.PrometheusReporter
metrics.reporter.prom.port: 9250
metrics.reporter.prom.factory.class: org.apache.flink.metrics.prometheus.PrometheusReporterFactory
